version: "3.9"
volumes:
  pg-data:
services:
  pg-friends:
    hostname: 'pg-friends'
    container_name: 'pg-friends'
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: friends
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d friends"]
      interval: 5s
      timeout: 5s
      retries: 5

  friends1:
    hostname: 'friends1'
    container_name: 'friends1'
    environment:
      DB_HOST: pg-friends:5432
      DB_NAME: friends
      DB_USER: postgres
      DB_PASSWORD: postgres
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg-friends

  friends2:
    hostname: 'friends2'
    container_name: 'friends2'
    environment:
      DB_HOST: pg-friends:5432
      DB_NAME: friends
      DB_USER: postgres
      DB_PASSWORD: postgres
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg-friends

  proxy:
    image: nginx:1.23.4
    container_name: 'proxy'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 80:80
    depends_on:
      - friends1
      - friends2
